loop-timeout: 5s

paloma:
  chain-id: paloma
  call-timeout: 20s
  keyring-dir: ~/.sparrow
  keyring-pass-env-name: PALOMA_KEYRING_PASS
  keyring-type: file
  signing-key-name: signing-key
  validator-address: ${PALOMA_VALIDATOR_ADDRESS}
  base-rpc-url: http://palomachain:26657
  gas-adjustment: 1.1
  gas-prices: 0.01dove
  account-prefix: paloma

terra:
  keyring-pass-env-name: TERRA_KEYRING_PASS
  acc-addresses:
    - acc1
    - acc2
    - acc3
